#!/usr/bin/env bash

options="shutdown\nreboot\nsuspend\ncancel\n"

selection="$(echo -e $options | \
             dmenu -i -p "start typing")"

case $selection in
	shutdown) systemctl poweroff
		exit 0
		;;
	reboot) systemctl reboot
		exit 0
		;;
	suspend) systemctl suspend
		exit 0
		;;
	cancel) exit 0
		;;
esac
